### ISSUE TITLE
dependabot

### ISSUE THREAD

**Issue by dermatz** [dermatz/mageforge#13]
https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#managing-dependabot-security-updates-for-your-repositories

bzw. 

https://docs.github.com/en/code-security/getting-started/quickstart-for-securing-your-repository

**Comment by dermatz** [comment]
![Image](https://github.com/user-attachments/assets/348e7469-86ca-4f41-adf1-7bdb62d99fa7)

**Comment by dermatz** [comment]
@Morgy93 was sollte noch in dem Ticket gemacht werden?

**Comment by Morgy93** [comment]
I don't have access to the settings. But that's it, thanks 🥳 Closed~
