### ISSUE TITLE
Basis-Setup

### ISSUE THREAD

**Issue by dermatz** [dermatz/mageforge#4]
Grundlegendes Magento 2 Modul, das erfolgreich registriert und aktiviert werden kann, um eine Basis für zukünftige Entwicklungen zu schaffen. Das Modul soll die minimal notwendige Struktur enthalten, damit es in Magento 2 funktioniert.

## Akzeptanzkriterien

- [x] Das Modul wird erfolgreich in Magento 2 registriert und aktiviert.
- [x] Die Verzeichnisstruktur und die erforderlichen Dateien (module.xml und registration.php) sind vorhanden und korrekt konfiguriert.
- [x] Nach der Aktivierung zeigt der Befehl php bin/magento module:status das Modul als aktiviert an.
- [x] Das Setup sollte nur die grundlegende Struktur enthalten, ohne zusätzliche Funktionen oder Anpassungen.

**Comment by Morgy93** [comment]
Done via #9
